ORMFoy5/Models/Bolum.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ORMFoy5.Models
{
    public class Bolum
    {
        [Key]
        public int BolumID { get; set; }

        [Required]
        public string BolumAd { get; set; }

        [ForeignKey("Fakulte")]
        public int FakulteID { get; set; }

        public virtual Fakulte Fakulte { get; set; }

        public virtual ICollection<Ogrenci> Ogrenciler { get; set; }

        public virtual ICollection<Ders> Dersler { get; set; } // << yeni
    }
}

ORMFoy5/Controllers/BolumController.cs
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using ORMFoy5.Models;
using System.Net;

namespace ORMFoy5.Controllers
{
    public class BolumController : Controller
    {
        private readonly AppDbContext _context;

        public BolumController()
        {
            _context = new AppDbContext();
        }

        // Index (Listele)
        public ActionResult Index()
        {
            var bolumler = _context.Bolumler.ToList();
            return View(bolumler);
        }

        // Create - GET
        public ActionResult Create()
        {
            ViewBag.FakulteID = new SelectList(_context.Fakulteler, "FakulteID", "FakulteAd");
            return View();
        }

        // Create - POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Bolum bolum)
        {
            if (ModelState.IsValid)
            {
                _context.Bolumler.Add(bolum);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FakulteID = new SelectList(_context.Fakulteler, "FakulteID", "FakulteAd", bolum.FakulteID);
            return View(bolum);
        }

        // Edit - GET
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var bolum = _context.Bolumler.Find(id);
            if (bolum == null)
            {
                return HttpNotFound();
            }
            ViewBag.FakulteID = new SelectList(_context.Fakulteler, "FakulteID", "FakulteAd", bolum.FakulteID);
            return View(bolum);
        }

        // Edit - POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Bolum bolum)
        {
            if (ModelState.IsValid)
            {
                var existingBolum = _context.Bolumler.Find(bolum.BolumID);
                if (existingBolum == null)
                {
                    return HttpNotFound();
                }

                existingBolum.BolumAd = bolum.BolumAd;
                existingBolum.FakulteID = bolum.FakulteID;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FakulteID = new SelectList(_context.Fakulteler, "FakulteID", "FakulteAd", bolum.FakulteID);
            return View(bolum);
        }

        // Details - GET
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var bolum = _context.Bolumler.Find(id);
            if (bolum == null)
            {
                return HttpNotFound();
            }
            return View(bolum);
        }

        // Delete - GET
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var bolum = _context.Bolumler.Find(id);
            if (bolum == null)
            {
                return HttpNotFound();
            }
            return View(bolum);
        }

        // Delete - POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var bolum = _context.Bolumler.Find(id);
            if (bolum == null)
            {
                return HttpNotFound();
            }
            _context.Bolumler.Remove(bolum);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ORMFoy5/Views/Bolum/Create.cshtml
@model ORMFoy5.Models.Bolum

@{
    ViewBag.Title = "Yeni Bölüm Ekle";
}

<h2>Yeni Bölüm Ekle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div>
            @Html.LabelFor(model => model.BolumAd, new { @class = "control-label" })
            @Html.EditorFor(model => model.BolumAd, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BolumAd, "", new { @class = "text-danger" })
        </div>
        <div>
            @Html.LabelFor(model => model.FakulteID, new { @class = "control-label" })
            @Html.DropDownList("FakulteID", (SelectList)ViewBag.FakulteID, "-- Seçiniz --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FakulteID, "", new { @class = "text-danger" })
        </div>
        <div>
            <input type="submit" value="Ekle" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ORMFoy5/Views/Bolum/Delete.cshtml
@model ORMFoy5.Models.Bolum

@{
    ViewBag.Title = "Bölüm Sil";
}

<h2>Bölüm Sil</h2>

@if (Model == null)
{
    <p>Hata: Bölüm bulunamadı.</p>
    <div>
        @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-default" })
    </div>
}
else
{
    <h3>Bölümü silmek istediğinizden emin misiniz?</h3>
    <div>
        <p><strong>Bölüm Adı:</strong> @Html.DisplayFor(model => model.BolumAd)</p>
        <p><strong>Fakülte:</strong> @Html.DisplayFor(model => model.Fakulte.FakulteAd)</p>
    </div>

    using (Html.BeginForm("Delete", "Bolum", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.BolumID)

        <div>
            <input type="submit" value="Sil" class="btn btn-danger" /> |
            @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
}

ORMFoy5/Views/Bolum/Details.cshtml
@model ORMFoy5.Models.Bolum

@{
    ViewBag.Title = "Bölüm Detayları";
}

<h2>Bölüm Detayları</h2>

@if (Model == null)
{
    <p>Hata: Bölüm bulunamadı.</p>
    <div>
        @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-default" })
    </div>
}
else
{
    <div>
        <p><strong>Bölüm Adı:</strong> @Html.DisplayFor(model => model.BolumAd)</p>
        <p><strong>Fakülte:</strong> @Html.DisplayFor(model => model.Fakulte.FakulteAd)</p>
    </div>

    <div>
        @Html.ActionLink("Düzenle", "Edit", new { id = Model.BolumID }, new { @class = "btn btn-primary" }) |
        @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-default" })
    </div>
}

ORMFoy5/Views/Bolum/Edit.cshtml
@model ORMFoy5.Models.Bolum

@{
    ViewBag.Title = "Bölüm Düzenle";
}

<h2>Bölüm Düzenle</h2>

@if (Model == null)
{
    <p>Hata: Bölüm bulunamadı.</p>
    <div>
        @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-default" })
    </div>
}
else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.BolumID)

        <div class="form-group">
            <div>
                @Html.LabelFor(model => model.BolumAd, new { @class = "control-label" })
                @Html.EditorFor(model => model.BolumAd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BolumAd, "", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(model => model.FakulteID, new { @class = "control-label" })
                @Html.DropDownList("FakulteID", (SelectList)ViewBag.FakulteID, "-- Seçiniz --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FakulteID, "", new { @class = "text-danger" })
            </div>
            <div>
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Listeye Geri Dön", "Index", null, new { @class = "btn btn-default" })
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ORMFoy5/Views/Bolum/Index.cshtml
@model IEnumerable<ORMFoy5.Models.Bolum>

@{
    ViewBag.Title = "Bölüm Listesi";
}

<h2>Bölüm Listesi</h2>

<p>
    @Html.ActionLink("Yeni Bölüm Ekle", "Create")
</p>

<table class="table">
    <tr>
        <th>Bölüm Adı</th>
        <th>Fakülte</th>
        <th>İşlemler</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.BolumAd)</td>
            <td>@Html.DisplayFor(modelItem => item.Fakulte.FakulteAd)</td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.BolumID }) |
                @Html.ActionLink("Detaylar", "Details", new { id = item.BolumID }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.BolumID })
            </td>
        </tr>
    }
</table>