ORMFoy5/Controllers/NotGirController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ORMFoy5.Models; // Models namespace'ini doğru tanımladık

namespace ORMFoy5.Controllers
{
    public class NotGirController : Controller
    {
        private readonly AppDbContext _context = new AppDbContext(); // AppDbContext tanımlı olmalı

        public ActionResult Index(int? dersID)
        {
            var dersler = _context.Dersler.ToList();
            ViewBag.Dersler = new SelectList(dersler, "DersID", "DersAd", dersID);

            if (!dersID.HasValue)
            {
                return View(new OgrenciDers[0]);
            }

            var ogrenciDersler = _context.OgrenciDersler
                .Include("Ogrenci")
                .Include("Ders")
                .Where(od => od.DersID == dersID)
                .ToList();

            return View(ogrenciDersler);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult KaydetNotlar(int[] ogrenciDersID, int[] vizeNotu, int[] finalNotu, int dersID)
        {
            for (int i = 0; i < ogrenciDersID.Length; i++)
            {
                var ogrenciDers = _context.OgrenciDersler.Find(ogrenciDersID[i]);
                if (ogrenciDers != null)
                {
                    ogrenciDers.VizeNotu = vizeNotu[i];
                    ogrenciDers.FinalNotu = finalNotu[i];
                }
            }
            _context.SaveChanges();

            var ogrenciDersler = _context.OgrenciDersler
                .Include("Ogrenci")
                .Include("Ders")
                .Where(od => od.DersID == dersID)
                .ToList();

            return View("NotlarKaydedildi", ogrenciDersler);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ORMFoy5/Views/NotGir/Index.cshtml
@using System.Web.Mvc
@using System.Web.Helpers
@using System.Linq

@model IEnumerable<ORMFoy5.Models.OgrenciDers>

@{
    ViewBag.Title = "Not Girişi";
}

<h2>Not Girişi</h2>

@using (Html.BeginForm("Index", "NotGir", FormMethod.Get))
{
    <div class="form-group">
        <label>Ders Seç:</label>
        @Html.DropDownList("dersID", (SelectList)ViewBag.Dersler, "-- Ders Seçiniz --", new { @class = "form-control", onchange = "this.form.submit()" })
    </div>
}

@if (Request.QueryString["dersID"] != null)
{
    if (Model.Any())
    {
        <form method="post" action="@Url.Action("KaydetNotlar", "NotGir")">
            @Html.AntiForgeryToken()
            <input type="hidden" name="dersID" value="@Request.QueryString["dersID"]" />
            <table class="table">
                <tr>
                    <th>Öğrenci Adı</th>
                    <th>Vize Notu</th>
                    <th>Final Notu</th>
                </tr>
                @{ int index = 0; }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Ogrenci.Ad</td>
                        <td>
                            <input type="hidden" name="ogrenciDersID[@index]" value="@item.OgrenciDersID" />
                            <input type="number" name="vizeNotu[@index]" value="@item.VizeNotu" class="form-control" min="0" max="100" />
                        </td>
                        <td>
                            <input type="number" name="finalNotu[@index]" value="@item.FinalNotu" class="form-control" min="0" max="100" />
                        </td>
                    </tr>
                    index++;
                }
            </table>
            <input type="submit" value="Notları Kaydet" class="btn btn-primary" />
        </form>
    }
    else
    {
        <p>Seçilen derse kayıtlı öğrenci bulunamadı. Lütfen önce bir öğrenci için ders ataması yapın.</p>
    }
}
else
{
    <p>Lütfen bir ders seçiniz.</p>
}

ORMFoy5/Views/NotGir/NotlarKaydedildi.cshtml
@model IEnumerable<ORMFoy5.Models.OgrenciDers>

@{
    ViewBag.Title = "Kaydedilen Notlar";
}

<h2>Kaydedilen Notlar</h2>

@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>Öğrenci Adı</th>
            <th>Ders Adı</th>
            <th>Vize Notu</th>
            <th>Final Notu</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Ogrenci.Ad</td>
                <td>@item.Ders.DersAd</td> 
                <td>@item.VizeNotu</td>
                <td>@item.FinalNotu</td>
            </tr>
        }
    </table>
    <p>@Html.ActionLink("Geri Dön", "Index", "NotGir")</p>
}
else
{
    <p>Kaydedilecek not bulunamadı.</p>
}